apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa1
---
apiVersion: v1
kind: Pod
metadata:
  name: p1
  labels:
    app: 'p1'
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
  - name: c1
    image: arunvel1988/c1
    ports:
    - containerPort: 8000
      name: http
  serviceAccountName: sa1
---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'service1'
  namespace: 'default'
  labels:
    app: ''
spec:
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000
  selector:
    app: 'p1'
  type: 'NodePort'
  loadBalancerIP: ''

